### ISSUE TITLE
The pictures mentioned in the articles have an odd black corner

### ISSUE THREAD

**Issue by Xuanwo** [tisonspieces/www-site#9]
https://github.com/tisonspieces/www-site/blob/63e5b8998403e93ae8c63af04bd5fd19aa54e6d3/blog/a-recap-of-apache-opendal-becoming-tlp.md?plain=1#L150

---

![image](https://github.com/tisonspieces/www-site/assets/5351546/bbd002ac-94ac-46d3-b5b1-7602058fe803)

**Comment by tisonkun** [comment]
This is a capture of "whole window" from Chrome. But we can improve it with a recapture. You're welcome to provide an attachment for use, or I'll do it myself when I'm back to my desktop.

**Comment by tisonkun** [comment]
Fixed in 7e5f8fa5afdf539731b8063d37106ad1bb3008c0
